const $=s=>document.querySelector(s);const cats=['魚図鑑','釣具・仕掛け','結び方','餌図鑑','釣り方・困りごと','食べ方・豆知識','安全・地域'];let category='魚図鑑',onlySaved=false,step=0,current=null,openedFromHash=false,lastFocus=null;let favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem('kashima-favorites-v1')||'[]'))}catch{};
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const norm=s=>s.toLowerCase().normalize('NFKC').replace(/[ぁ-ゖ]/g,c=>String.fromCharCode(c.charCodeAt(0)+96)).replace(/\s/g,'');
function sourceHtml(item){return `<div class="sources">参考資料・確認日：${CHECKED}${(item.sources||[]).map(k=>SOURCES[k]?`<a href="${SOURCES[k][1]}" target="_blank" rel="noopener noreferrer">${esc(SOURCES[k][0])} ↗</a>`:'').join('')}${item.cat==='魚図鑑'?'<p>季節と釣り方は一般的な目安。当地の釣果や立入許可を保証しません。</p>':''}</div>`}
function save(id){if(favorites.has(id))favorites.delete(id);else favorites.add(id);try{localStorage.setItem('kashima-favorites-v1',JSON.stringify([...favorites]))}catch{toast('このブラウザーでは保存できません')}render();if(current?.id===id)updateSave();toast(favorites.has(id)?'この端末に保存しました':'保存を解除しました')}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',2300)}
function art(item){return item.color?fishArt(item):guideArt(item)}
function render(){const query=norm($('#query').value),water=$('#habitat').value,season=$('#season').value,danger=$('#danger').checked;$('#saveCount').textContent=favorites.size;$('#saved').setAttribute('aria-pressed',onlySaved);$('#categories').innerHTML=cats.map(c=>`<button data-cat="${c}" aria-pressed="${category===c&&!onlySaved}">${c}<span>${ITEMS.filter(x=>x.cat===c).length}</span></button>`).join('');$('#filters').hidden=!(category==='魚図鑑'||query||onlySaved);const list=ITEMS.filter(x=>(query||onlySaved||x.cat===category)&&(!onlySaved||favorites.has(x.id))&&(!query||norm(JSON.stringify(x)).includes(query))&&(!water||x.water?.includes(water))&&(!season||x.seasons?.includes(season))&&(!danger||x.danger));$('#sectionTitle').textContent=onlySaved?'保存した手帖':query?'手帖の検索結果':category==='魚図鑑'?'魚を知る':category;$('#count').textContent=`${list.length}件`;$('#scope').textContent=category==='魚図鑑'&&!query&&!onlySaved?'季節は一般的な目安。当地の実績・生息情報は参考資料で確認してください。海・汽水・淡水をまとめて探せます。':onlySaved?'お気に入りは、この端末のブラウザーに保存されます。':query?'検索は全項目が対象です。水域・季節を選ぶと魚図鑑の項目に絞られます。':'図を見て、使い方と注意点を確認。';$('#results').innerHTML=list.length?list.map(x=>`<article class="card"><button class="card-open" data-open="${x.id}"><div class="art ${x.cat==='餌図鑑'?'bait':x.cat==='魚図鑑'?'':'guide'}"><span class="specimen">${x.number?'NO. '+x.number:x.cat}</span>${art(x)}<span class="habitat-tag">${x.water||'GUIDE'}</span></div><div class="card-body"><h3>${x.name}</h3><p>${x.summary}</p><div class="tags">${x.seasons?`<span class="tag">${x.seasons}</span>`:`<span class="tag">${x.steps?(x.textOnly?'手順解説':'段階図')+'・'+x.steps.length+'ステップ':x.cat}</span>`}${x.danger?'<span class="tag warning">取扱い注意</span>':''}</div></div></button><button class="star" data-save="${x.id}" aria-label="${x.name}を${favorites.has(x.id)?'保存解除':'保存'}" aria-pressed="${favorites.has(x.id)}">${favorites.has(x.id)?'★':'☆'}</button></article>`).join(''):'<div class="empty"><h3>該当する項目がありません</h3><p>検索語を短くするか、水域・季節の条件を解除してください。</p><button id="emptyReset" class="primary">すべての条件を解除</button></div>'}
function reset(){['query','habitat','season'].forEach(k=>$('#'+k).value='');$('#danger').checked=false;onlySaved=false;render()}
function openItem(id,push=true){const x=ITEMS.find(x=>x.id===id);if(!x)return;if(push){history.pushState({detail:true,depth:(history.state?.depth||0)+1},'',`#${id}`);openedFromHash=false}current=x;step=0;lastFocus=document.activeElement;const facts=x.cat==='魚図鑑'?`<div class="art detail-art">${fishArt(x)}</div><div class="facts"><div class="fact"><h3>水域・季節の目安</h3><p>${x.water} ／ ${x.seasons}</p></div><div class="fact"><h3>${x.naturalFood?'自然界で食べるもの':'食べるもの・釣り餌'}</h3><p>${x.naturalFood||x.food}</p></div>${x.baitAdvice?`<div class="fact"><h3>この手帖での釣り方</h3><p>${x.baitAdvice}</p></div>`:''}</div><div class="article"><h3>見分ける手がかり</h3><p>${x.identify}</p><h3>狙い方の基本</h3><p>${x.method}</p>${typeof jumpHtml==='function'?jumpHtml(x):''}</div>${x.local?`<div class="fact"><h3>当地の確認情報</h3><p>${x.local}</p></div>`:""}<div class="note"><strong>気をつけること</strong><br>${x.warning}</div>${typeof ecologyHtml==='function'?ecologyHtml(x):''}${typeof tackleHtml==='function'?tackleHtml(x):''}${typeof kitchenHtml==='function'?kitchenHtml(x):''}`:'';$('#detailContent').innerHTML=`<div class="detail-inner"><div class="detail-title"><div><small>${x.cat}${x.number?' / NO. '+x.number:''}</small><h2>${x.name}</h2></div><button id="detailSave" class="outline" data-save="${x.id}"></button></div><p class="lead">${x.summary}</p>${facts}${x.color&&x.cat!=="魚図鑑"?`<div class="art detail-art">${fishArt(x)}</div>`:""}${x.diagram?rigDiagram(x.diagram)+'<p class="source-label">構成を理解するための模式図。縮尺・仕掛けの長さは実物と異なります。</p>':''}${x.warning&&x.cat!=='魚図鑑'?`<div class="note">${x.warning}</div>`:''}${x.steps?'<div class="note">結びは素材・太さ・製品の指示に合わせて選びます。PEへ単糸用の巻き数をそのまま適用しないこと。強度を保証するものではありません。</div><div id="knot"></div>':`<div class="article">${(x.sections||[]).map(s=>`<h3>${s[0]}</h3><p>${s[1]}</p>`).join('')}</div>`}<h3>あわせて読む</h3><div class="related">${(x.related||[]).map(id=>ITEMS.find(t=>t.id===id)).filter(Boolean).map(t=>`<button data-open="${t.id}">${t.name}</button>`).join('')}</div>${sourceHtml(x)}</div>`;updateSave();if(x.steps)renderStep();if(!$('#detail').open)$('#detail').showModal();document.body.classList.add('modal-open');$('#detail').scrollTop=0;$('#close').focus();}
function updateSave(){$('#detailSave').textContent=favorites.has(current.id)?'★ 保存済み':'☆ 保存';$('#detailSave').setAttribute('aria-pressed',favorites.has(current.id))}
function renderStep(){const x=current,s=x.steps[step];$('#knot').innerHTML=`<div class="knot-panel"><div class="stepbar"><strong>${step+1} / ${x.steps.length}</strong>${x.textOnly?'':'<button id="zoom" class="textbutton" aria-pressed="false">図を拡大</button>'}</div>${x.textOnly?'<p class="note">この結びは文章の手順解説です。立体的な通し方は、下の公式手順の図と照合しながら練習してください。</p>':`<div class="knot-image"><img src="assets/${x.id}-${step+1}.svg" alt="${x.name} 手順${step+1}：${s[0]}。公式手順に基づく独自模式図"></div>`}<div class="steptext" aria-live="polite"><h3>${step+1}. ${s[0]}</h3><p>${s[1]}</p></div><p class="legend">本線＝竿側に続く長い糸 ／ 端糸＝結びに使う短い先端<br>${x.textOnly?'まず太いひもで練習し、実際の糸で滑りを確認。':'図の矢印＝糸を動かす方向。重なりは途切れない側が手前です。'}</p><div class="stepbar"><button class="outline" id="prevStep" ${step===0?'disabled':''}>前の手順</button><button class="primary" id="nextStep" ${step===x.steps.length-1?'disabled':''}>次の手順</button></div></div><p class="source-label">${x.textOnly?'手順出典：':'独自模式図・手順出典：'}${SOURCES[x.id][0]}。<a href="${SOURCES[x.id][1]}" target="_blank" rel="noopener noreferrer">原典で全手順を見る ↗</a></p>`;}
function closeDetail(){if(!$('#detail').open)return;if(location.hash&&!openedFromHash){history.go(-(history.state?.depth||1))}else{history.replaceState(null,'',location.pathname+location.search);hideDetail()}}
function hideDetail(){$('#detail').close();document.body.classList.remove('modal-open');current=null;lastFocus?.focus()}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.open)openItem(b.dataset.open);if(b.dataset.save)save(b.dataset.save);if(b.dataset.cat){category=b.dataset.cat;onlySaved=false;$('#habitat').value='';$('#season').value='';$('#danger').checked=false;$('#query').value='';render()}if(b.id==='saved'){onlySaved=!onlySaved;$('#habitat').value='';$('#season').value='';$('#danger').checked=false;$('#query').value='';render()}if(['reset','emptyReset'].includes(b.id))reset();if(['back','close'].includes(b.id))closeDetail();if(b.id==='prevStep'&&step>0){step--;renderStep()}if(b.id==='nextStep'&&step<current.steps.length-1){step++;renderStep()}if(b.id==='zoom'){const z=$('.knot-image').classList.toggle('zoom');b.textContent=z?'図を縮小':'図を拡大';b.setAttribute('aria-pressed',z)}});
['query','habitat','season','danger'].forEach(id=>$('#'+id).addEventListener(id==='query'?'input':'change',render));$('#detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail()});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail()}});window.addEventListener('popstate',()=>{if(location.hash){const id=decodeURIComponent(location.hash.slice(1));openItem(id,false)}else hideDetail()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!$('#detail').open&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#query').focus()}});render();if(location.hash){openedFromHash=true;openItem(decodeURIComponent(location.hash.slice(1)),false)}

document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.dock)window.scrollTo({top:0,behavior:"smooth"});if(b.dataset.action==="search"){window.scrollTo({top:0,behavior:"smooth"});$("#query").focus()}if(b.dataset.action==="saved"){$("#saved").click();window.scrollTo({top:0,behavior:"smooth"})}});
