Object.assign(SOURCES,{
park:['鹿島港魚釣園｜利用案内','https://kashima-fa.com/infomation/'],parkfish:['鹿島港魚釣園｜釣り場・魚種紹介','https://kashima-fa.com/fishingsopt/'],parksep:['鹿島港魚釣園｜2026年9月釣果（実績）','https://kashima-fa.com/2026%E5%B9%B49%E6%9C%88%EF%BC%88%E6%9C%80%E6%96%B0%E6%9B%B4%E6%96%B0%E6%97%A59%E6%9C%881%E6%97%A5%EF%BC%89/'],parkoct:['鹿島港魚釣園｜2026年10月釣果（実績）','https://kashima-fa.com/2026%E5%B9%B410%E6%9C%88%EF%BC%88%E6%9C%80%E6%96%B0%E6%9B%B4%E6%96%B0%E6%97%A510%E6%9C%881%E6%97%A5%EF%BC%89/'],kitaura:['鹿嶋市｜北浦の生息魚紹介','https://www.city.kashima.ibaraki.jp/site/kankou/3059.html'],fresh:['国土交通省｜霞ヶ浦の淡水魚','https://www.ktr.mlit.go.jp/kasumi/kasumi00076.html'],lakerules:['茨城県｜霞ヶ浦・北浦の釣りのルール','https://www.pref.ibaraki.jp/nourinsuisan/kasui/contents/ruleandmanner.html'],searules:['茨城県｜海の採捕サイズ等（2026年4月版）','https://www.pref.ibaraki.jp/nourinsuisan/gyosei/chosei/documents/documents/makietirasi260401.pdf'],danger:['DAIWA｜危険な魚・トラブル','https://www.daiwa.com/jp/beginner/faq/'],life:['海上保安庁｜釣りとライフジャケット','https://www6.kaiho.mlit.go.jp/watersafety/fishing/31_life/index.html'],nikkawa:['神栖市｜日川浜海水浴場','https://www.city.kamisu.ibaraki.jp/kanko_sports/ss_facility/1002393/1002408/1002409.html'],river:['茨城県｜川・湖沼での釣り','https://www.pref.ibaraki.jp/koho/kurashi-qanda/kyoiku-bunka/yoka-recreation/kawa_kosyou.html'],funaBio:['茨城県水産試験場｜ギンブナ（2011年）','https://www.pref.ibaraki.jp/nourinsuisan/naisuishi/gyogancho/documents/034_ginbuna.pdf'],genBio:['茨城県水産試験場｜ゲンゴロウブナ（2011年）','https://www.pref.ibaraki.jp/nourinsuisan/naisuishi/gyogancho/documents/036_gengoroubuna.pdf'],channelBio:['茨城県水産試験場｜チャネルキャットフィッシュ（2011年）','https://www.pref.ibaraki.jp/nourinsuisan/naisuishi/gyogancho/documents/055_channel_catfish_1.pdf'],nigoiBio:['茨城県水産試験場｜ニゴイ（2011年）','https://www.pref.ibaraki.jp/nourinsuisan/naisuishi/gyogancho/documents/060_nigoi.pdf'],wakaBio:['茨城県水産試験場｜ワカサギ（2011年）','https://www.pref.ibaraki.jp/nourinsuisan/naisuishi/documents/079_wakasagi.pdf'],alien:['茨城県水産試験場｜他所からきた魚たち','https://www.pref.ibaraki.jp/nourinsuisan/naisuishi/gyogancho/colunm.html'],alienlaw:['環境省｜外来生物法Q&A','https://www.env.go.jp/nature/intro/1law/qa.html'],rigbottom:['SHIMANO｜探り・胴突釣り','https://fish.shimano.com/ja-JP/content/beginners/fishingstyle/baitfishing/saguri/index.html'],rigfuna:['DAIWA｜ヘラブナ・マブナの釣り','https://www.daiwa.com/jp/beginner/place/herabuna_uki'],rigsabiki:['DAIWA｜サビキ釣り','https://www.daiwa.com/jp/beginner/place/sabiki'],rignage:['DAIWA｜ちょい投げ','https://www.daiwa.com/jp/beginner/place/nage'],baitasari:['DAIWA｜カワハギ・アサリの付け方','https://www.daiwa.com/jp/beginner/place/kawahagi'],jig:['SHIMANO｜ライトソルト準備','https://fish.shimano.com/ja-JP/content/fishingstyle/article/salt_beginner/l-game/preparation.html'],material:['サンライン｜素材の特徴','https://fishing.sunline.co.jp/material/']});
const extraFish=[
['sayori','サヨリ','海','春 秋','長く伸びるのは下あご。ダツとの違いを確認。','小さなオキアミなど','表層を小針のウキ仕掛けで探る。寄せ餌は許可区域だけ。','下あごが長く、上あごは短い。ダツは上下とも長い。','細いあご・針に注意。まき餌規制を守る。','halfbeak','#88a99e',false,'sayori'],
['anago','マアナゴ','海','夏 秋','長い体の側面に白点。夜行性の底魚。','魚の切り身・アオイソメ','底付近の餌釣り。安全な許可区域で行い、夜は単独行動を避ける。','体側に白い点が並ぶ。ウナギ類とは体色だけで区別しない。','針を飲まれたら無理に指を入れない。生食しない。','eel','#8f8969',false,'anago'],
['magochi','マゴチ','海','夏 秋','平たい大きな頭と上向きの目。砂底の待ち伏せ役。','小魚・ルアー','砂底近くをワームなどで探る。無理に入水せず、波から距離を取る。','頭が上下に平たく、尾へ向かって細くなる。','えらぶたの棘に注意。素手で握らず道具を使う。','goby','#9e8960',true,'magochi'],
['ishimochi','イシモチ類','海','夏 秋','ニベ・シログチなどの総称。銀色の底生魚。','アオイソメなど','砂泥底の餌釣り。底付近で待ち、時々餌を確認する。','ニベとシログチなどを含む呼び名。えらぶたの斑紋など複数の特徴を見る。','呼び名だけで種を確定しない。棘と針に注意。','bass','#aab0a0',false,'ishimochi'],
['umitanago','ウミタナゴ類','海','春 秋','高い体と小さな口。ゆっくり餌を漂わせる。','小エビ・虫餌','小針のウキ仕掛けで、層を変えて探る。まき餌規制に注意。','平たい体と小さな口。種類・成長で模様は異なる。','小さな魚でも背びれと針先に注意。','deep','#b7ab94',false,'umitanago'],
['mejina','メジナ','海','春 秋 冬','丸みのある黒緑色の体と小さな口。','海藻・オキアミなど','ウキ釣りで層を探る。まき餌を使う場合は指定区域と量を守る。','丸い体と小さな口、広い尾びれ。クロダイより丸い輪郭。','背びれの棘・えらに注意。大型はタモを使う。','deep','#50746b',true,'mejina'],
['buri','ブリの若魚','海','夏 秋','ワカシ・イナダは成長名。同じブリの若魚。','小魚・メタルジグ','回遊があるときに小型ジグなどで探る。投げる周囲を確かめる。','黄色の縦帯と深い二又の尾。成長名は地方により異なる。','若魚でもよく走る。大物を細い糸で抜き上げない。','yellowtail','#588c85',false,'buri'],
['kanpachi','カンパチの若魚','海','夏 秋','ショゴと呼ばれる若魚。頭の帯模様が目印。','小魚・ルアー','小型青物向けルアー。回遊次第で、釣れることは保証できない。','目を通る暗い斜め帯。ブリの成長名とは別種。','引きが強い。竿・糸・金具の適合とドラグを確認。','yellowtail','#8a9971',false,'kanpachi'],
['kamasu','カマス類','海','夏 秋','細長い体と大きな口。鋭い歯が並ぶ。','小魚・小型ルアー','小型ルアーで回遊層を探る。傷ついたリーダーを交換する。','長い口と目立つ歯。種類の判別は鰭や体色だけで断定しない。','歯に指を近づけない。長いプライヤーを使う。','slender','#86a19b',true,'kamasu'],
['gengoro','ゲンゴロウブナ（ヘラブナ）','淡水','春 夏 秋','高い体と、小さめの頭。フナ類は同定が難しい。','ヘラ用練り餌','底を測り、ウキ下を合わせる。北浦ではまき餌禁止が優先。','高い体が手がかりだが、フナ類を体形だけで確定しない。','北浦のまき餌禁止を守り、大型はタモへ。','deep','#9c9f83',false,'genBio'],
['channelcat','アメリカナマズ','淡水','夏 秋','チャネルキャットフィッシュ。二又の尾と棘に注意。','虫餌・魚の切り身など','底で餌を待つ。掛かったら素手でつかまず、棘の位置を確認。','尾が深く二又に分かれる。日本のナマズは丸みのある尾。口周りにひげがある。','背・胸びれの硬い棘でけがをする。特定外来生物を生きたまま運ばない。','channel','#8b9482',true,'channelBio'],
['nigoi','ニゴイ','淡水','春 夏 秋','突き出た吻と下向きの口。砂底で餌を探す。','虫餌・ルアーなど','底を意識した餌釣り。河川の遊漁規則を先に確認する。','コイより長い吻、下向きの口と1対の口ひげ。','似た種類との判別は慎重に。大きな魚はタモで取り込む。','carp','#9c997c',false,'nigoiBio'],
['blackbass','オオクチバス','淡水','春 夏 秋','大きな口と体側の暗色帯。外来魚の取扱いを守る。','小魚・甲殻類を模したルアー','小さなワームなどで岸際の変化を探る。立入と駐車の許可を確認。','口が大きく、上あご後端が目の後方に達する。','特定外来生物。生きたまま持ち出し・他水域へ放流しない。岸へ捨てない。','bass','#78906b',false,'alien'],
['bluegill','ブルーギル','淡水','春 夏 秋','丸い体に縦帯、えらぶた後端の黒い斑。','虫餌・小さなワーム','小さな針で岸近くの層を探る。管理者・県の規則を優先。','体が丸く、えらぶた後端に黒い張り出しがある。','背びれの棘に注意。特定外来生物を生きたまま運ばない。','deep','#84977a',true,'alien']
];
for(const r of extraFish){const f={id:r[0],name:r[1],cat:'魚図鑑',water:r[2],seasons:r[3],summary:r[4],food:r[5],method:r[6],identify:r[7],warning:r[8],shape:r[9],color:r[10],danger:r[11],sources:[],related:r[2]==='淡水'?['float','line','safety']:['cast','line','safety']};if(r[2]==='海'){SOURCES['bio_'+f.id]=['Honda釣り倶楽部｜'+f.name+'の一般生態','https://www.honda.co.jp/fishing/picture-book/'+r[12]+'/'];f.sources=['bio_'+f.id,'parkfish','port'];f.local='魚釣園等の公式魚種紹介を地域資料として参照。直近の釣果・同定・出現月を保証するものではありません。'}else{f.sources=[r[12],'lake','lakerules'];f.local='霞ヶ浦・北浦水系の公的な生息資料を参照。過去の記録であり、現在の個別地点の釣果や立入可否は示しません。'}FISH.push(f);ITEMS.push(f);}
for(const id of ['namazu','unagi']){FISH.splice(FISH.findIndex(x=>x.id===id),1);ITEMS.splice(ITEMS.findIndex(x=>x.id===id),1)}
for(const id of ['fugu','stingray','gonzui']){const f=ITEMS.find(x=>x.id===id);FISH.splice(FISH.findIndex(x=>x.id===id),1);f.cat='安全・地域';f.sections=[['見分ける手がかり',f.identify],['取扱いの注意',f.warning],['掛かったとき',f.method]];f.sources=['danger','life'];f.summary=f.warning;}
const bioMap={aji:'maaji',saba:'masaba',iwashi:'maiwashi',sillago:'shirogisu',hirame:'hirame',karei:'makogarei',mebaru:'mebaru',kasago:'kasago',ainame:'ainame',kurodai:'kurodai',suzuki:'suzuki',haze:'mahaze',bora:'bora',kawahagi:'kawahagi',datsu:'datsu'};
for(const f of FISH){if(bioMap[f.id]){SOURCES['bio_'+f.id]=['Honda釣り倶楽部｜'+f.name+'の一般生態','https://www.honda.co.jp/fishing/picture-book/'+bioMap[f.id]+'/'];f.sources=['bio_'+f.id,'port'];f.local='一般図鑑の生態・釣期と、当地の釣り場ルールは別の情報です。施設の最新記録を確認してください。'}if(['kawahagi','datsu','aji','sillago','mebaru'].includes(f.id)){f.sources.push('parksep');f.local='鹿島港魚釣園の2026年9月公式釣果に記載があります。釣果の総称から細かな種まで確定するものではありません。'}if(['hirame','saba'].includes(f.id)){f.sources.push('parkoct');f.local='鹿島港魚釣園の2026年10月3日の釣果に記載。サバなどの総称は種を確定する情報ではありません。'}if(f.id==='funa'){f.sources=['funaBio','rigfuna','lakerules'];f.local='茨城県のギンブナ生態資料（2011年）を参照。フナ類は形態が似ており、イラストだけで種を確定できません。'}if(f.id==='koi'){f.sources=['kitaura','lakerules'];f.local='鹿嶋市の北浦紹介に生息魚として記載。現在の資源量や各地点の釣果を示すものではありません。'}if(f.id==='wakasagi'){f.sources=['wakaBio','lakerules'];f.local='県の霞ヶ浦・北浦水系の生息資料を参照（2011年）。';f.warning='霞ヶ浦北浦では1/21〜2月末日・5/1〜7/20は採捕禁止。禁漁期間とサイズ・漁具等の最新規則を確認。'}if(f.id==='hirame')f.sources.push('searules');if(f.id==='umazura'){f.sources=['parkfish','port'];f.local='一般的なカワハギ類との見分けを扱います。当地での直近の種別実績はこのカードでは確認していません。'}f.number=String(FISH.indexOf(f)+1).padStart(2,'0');}
const setSource=(id,ss)=>{const x=ITEMS.find(x=>x.id===id);if(x)x.sources=ss};setSource('float',['rigfuna','lake']);setSource('bottom',['rigbottom','baitasari','port']);setSource('sabiki',['rigsabiki','chum']);setSource('asari',['baitasari']);setSource('isome',['rignage']);setSource('worm',['rigfuna']);setSource('paste',['rigfuna','lake']);setSource('ami',['rigsabiki','chum']);setSource('fishbait',['rigbottom']);setSource('line',['line','material']);setSource('safety',['port','chum','lake','lakerules','searules','life']);
const safe=ITEMS.find(x=>x.id==='safety');safe.sections.splice(3,0,['魚種ごとの採捕規制','茨城県海面のヒラメは全長30cm未満を採捕しない。霞ヶ浦北浦ではワカサギは1/21〜2月末日、5/1〜7/20が禁漁、ウナギは23cm以下を採捕しない。場所の境界と最新規則を確認してください。'],['外来魚は生きたまま運ばない','バス・ブルーギル・アメリカナマズ等は生きたままの移動・持ち込みをしない。霞ヶ浦北浦では釣ったその場での再放流は制限されていません。岸へ放置・投棄しないでください。']);
ITEMS.push({id:'places',name:'水域別・釣行前の確認',cat:'安全・地域',summary:'魚釣園、海岸、北浦、河川を分けて確認する。',sections:[['鹿島港魚釣園','公式の釣り施設。営業・荒天休園・料金・使用仕掛けは利用案内で確認。救命胴衣を着用し、竿は1人2本まで。投げ方は混雑状況と職員の指示を優先。魚釣園以外の鹿島港へは釣りに入らないでください。'],['日川浜海岸','神栖市は釣りを楽しめる海岸として紹介しています。周辺の港湾施設の開放を意味しません。海水浴・工事・現地区画・立入掲示を確認し、遊泳者やサーファーの近くに投げないこと。'],['北浦','まき餌禁止。遊漁券が不要でも、保護水面・管理施設・漁具・魚種・期間の制限があります。農作業や漁業、通行を妨げない駐車を。'],['利根川・常陸利根川・接続水路','具体的地点の管轄、漁業権、遊漁券の対象を確認。北浦の規則を河川へ一律に当てはめない。堰・水門・私有地・工事区域へ入らず、増水や放流に注意。']],sources:['park','port','nikkawa','lake','lakerules','river'],related:['safety','cast']});
ITEMS.find(x=>x.id==='safety').related.push('places');ITEMS.find(x=>x.id==='sources').sources=Object.keys(SOURCES);
